In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle datasets download -d tmdb/tmdb-movie-metadata

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Downloading tmdb-movie-metadata.zip to /content
  0% 0.00/8.89M [00:00<?, ?B/s]
100% 8.89M/8.89M [00:00<00:00, 145MB/s]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import zipfile
zip_ref = zipfile.ZipFile('/content/tmdb-movie-metadata.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

In [5]:
movies=pd.read_csv('/content/tmdb_5000_movies.csv')
credits=pd.read_csv('/content/tmdb_5000_credits.csv')

NameError: ignored

In [3]:
movies.head(1).shape

NameError: ignored

In [ ]:
credits.head(1).shape

In [4]:
movies.info()
#genre,id,keywords,title,overview,

NameError: ignored

In [ ]:
movies['id'][0]

19995

In [ ]:
credits.info()
#title,id,cast,crew

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [ ]:
credits['movie_id'][0]

19995

In [ ]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [ ]:
movies=movies.merge(credits,on='title')

In [ ]:
movies.shape

(4809, 23)

In [ ]:
movies.head(1).info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1 entries, 0 to 0
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                1 non-null      int64
 1   genres                1 non-null      object
 2   homepage              1 non-null      object
 3   id                    1 non-null      int64
 4   keywords              1 non-null      object
 5   original_language     1 non-null      object
 6   original_title        1 non-null      object
 7   overview              1 non-null      object
 8   popularity            1 non-null      float64
 9   production_companies  1 non-null      object
 10  production_countries  1 non-null      object
 11  release_date          1 non-null      object
 12  revenue               1 non-null      int64
 13  runtime               1 non-null      float64
 14  spoken_languages      1 non-null      object
 15  status                1 non-null      object
 16  tagline               1 non-null      object
 17  title                 1 non-null      object
 18  vote_average          1 non-null      float64
 19  vote_count            1 non-null      int64
 20  movie_id              1 non-null      int64
 21  cast                  1 non-null      object
 22  crew                  1 non-null      object
dtypes: float64(3), int64(5), object(15)
memory usage: 192.0+ bytes

In [ ]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [ ]:
movies.shape

(4809, 23)

In [ ]:
df = movies[['id','title','genres','overview','keywords','cast','crew']]

In [ ]:
df.head()

,id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4809 non-null   int64
 1   title     4809 non-null   object
 2   genres    4809 non-null   object
 3   overview  4806 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [ ]:
df.shape

(4809, 7)

In [ ]:
df['overview'].isnull().sum()

3

In [ ]:
df.dropna(inplace=True)

<ipython-input-134-c64f9f573c18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [ ]:
df.shape

(4806, 7)

In [ ]:
df.isnull().sum()

id          0
title       0
genres      0
overview    0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4806 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4806 non-null   int64
 1   title     4806 non-null   object
 2   genres    4806 non-null   object
 3   overview  4806 non-null   object
 4   keywords  4806 non-null   object
 5   cast      4806 non-null   object
 6   crew      4806 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.4+ KB

In [ ]:
df['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4806, dtype: object

In [ ]:
import ast

In [ ]:
def convert(text):
  l=[]
  for i in ast.literal_eval(text):
    l.append(i['name'])
    # print(i)
    # break

  return l

In [ ]:
ast.literal_eval('[{"id": 28, "name": "Action"}]')

[{'id': 28, 'name': 'Action'}]

In [ ]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
df['genres']=df['genres'].apply(convert)

<ipython-input-143-dc06b88fa6dd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres']=df['genres'].apply(convert)

In [ ]:
df.head(1)

,id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
df['keywords']=df['keywords'].apply(convert)

<ipython-input-145-e88a987365bf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords']=df['keywords'].apply(convert)

In [ ]:
def convert_cast(text):
  l=[]
  count=0
  for i in ast.literal_eval(text):
    if count <3:
     l.append(i['name'])
    else:
      break
    # print(i)
    # break

  return l

In [ ]:

def convert_crew(text):
  l=[]
  for i in ast.literal_eval(text):
    if i['job']=='Director':
       l.append(i['name'])
    # print(i)
    # break

  return l

In [1]:
df['cast']=df['cast'].apply(convert_cast)

NameError: ignored

In [ ]:
df['crew']=df['crew'].apply(convert_crew)

<ipython-input-151-d413a5e80c86>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew']=df['crew'].apply(convert_crew)

In [ ]:
df.head(1)

,id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]

In [ ]:
df.sample(5)

,id,title,genres,overview,keywords,cast,crew
757,87825,Trouble with the Curve,"[Drama, Romance]","Slowed by age and failing eyesight, crack base...","[women, baseball, pitcher, home run, aging, sp...","[Clint Eastwood, Amy Adams, Justin Timberlake,...",[Robert Lorenz]
3883,8841,The Class,[Drama],Teacher and novelist François Bégaudeau plays ...,"[paris, socially deprived family, literature, ...","[François Bégaudeau, Franck Keïta, Esmeralda O...",[Laurent Cantet]
754,16866,Planet 51,"[Science Fiction, Animation, Family, Comedy, A...",When Earth astronaut Capt. Chuck Baker arrives...,"[flying saucer, alien life-form, spaceship, al...","[Dwayne Johnson, Seann William Scott, Jessica ...","[Jorge Blanco, Javier Abad, Marcos Martínez]"
3023,22824,The Fourth Kind,"[Mystery, Science Fiction, Thriller]","Since the 1960s, a disproportionate number of ...","[brother sister relationship, wheelchair, hypn...","[Milla Jovovich, Will Patton, Hakeem Kae-Kazim...",[Olatunde Osunsanmi]
2288,4232,Scream,"[Crime, Horror, Mystery]",A killer known as Ghostface begins killing off...,"[halloween, gore, serial killer, slasher, tabl...","[David Arquette, Neve Campbell, Courteney Cox,...",[Wes Craven]

In [ ]:
def collapse(L):
  l=[]
  for i in L:
    l.append(i.replace(" ",""))
  return l

In [ ]:
df['cast'] = df['cast'].apply(collapse)
df['crew'] = df['crew'].apply(collapse)
df['genres'] = df['genres'].apply(collapse)
df['keywords'] = df['keywords'].apply(collapse)

<ipython-input-157-2391b60870b5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast'] = df['cast'].apply(collapse)
<ipython-input-157-2391b60870b5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew'] = df['crew'].apply(collapse)
<ipython-input-157-2391b60870b5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(collapse)
<ipython-input-157-2391b60870b5>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords'] = df['keywords'].apply(collapse)

In [ ]:
df.head(1)

,id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","In the 22nd century, a paraplegic Marine is di...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]

In [ ]:
df['overview']=df['overview'].apply(lambda x: x.split(" "))

<ipython-input-165-fe00188e833e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview']=df['overview'].apply(lambda x: x.split(" "))

In [ ]:
df['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [ ]:
df['overview'].info()

<class 'pandas.core.series.Series'>
Int64Index: 4806 entries, 0 to 4808
Series name: overview
Non-Null Count  Dtype
--------------  -----
4806 non-null   object
dtypes: object(1)
memory usage: 204.1+ KB

In [ ]:
df['tag']=df['genres']+df['overview']+df['keywords']+df['crew']+df['cast']

<ipython-input-168-8cfe790f6c2f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag']=df['genres']+df['overview']+df['keywords']+df['crew']+df['cast']

In [ ]:
df

,id,title,genres,overview,keywords,cast,crew,tag
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, I..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Adventure, Fantasy, Action, Captain, Barbossa..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[Action, Adventure, Crime, A, cryptic, message..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Action, Crime, Drama, Thriller, Following, th..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[Action, Adventure, ScienceFiction, John, Cart..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[El, Mariachi, just, wants, to, play, his, gui...","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",[RobertRodriguez],"[Action, Crime, Thriller, El, Mariachi, just, ..."
4805,72766,Newlyweds,"[Comedy, Romance]","[A, newlywed, couple's, honeymoon, is, upended...",[],"[EdwardBurns, KerryBishé, MarshaDietlein, Cait...",[EdwardBurns],"[Comedy, Romance, A, newlywed, couple's, honey..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie]","[""Signed,, Sealed,, Delivered"", introduces, a,...","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe, GeoffG...",[ScottSmith],"[Comedy, Drama, Romance, TVMovie, ""Signed,, Se..."
4807,126186,Shanghai Calling,[],"[When, ambitious, New, York, attorney, Sam, is...",[],"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,[Documentary],"[Ever, since, the, second, grade, when, he, fi...","[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...","[BrianHerzlinger, JonGunn, BrettWinn]","[Documentary, Ever, since, the, second, grade,..."

In [ ]:
df.head(1)['tag']

0    [Action, Adventure, Fantasy, ScienceFiction, I...
Name: tag, dtype: object

In [ ]:
df.drop(['genres','overview','keywords','crew','cast'],axis=1,inplace=True)

<ipython-input-176-e3e3671c13b7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['genres','overview','keywords','crew','cast'],axis=1,inplace=True)

In [ ]:
df.head(1)

      id   title                                                tag
0  19995  Avatar  [Action, Adventure, Fantasy, ScienceFiction, I...

In [ ]:
df['tag']

0       [Action, Adventure, Fantasy, ScienceFiction, I...
1       [Adventure, Fantasy, Action, Captain, Barbossa...
2       [Action, Adventure, Crime, A, cryptic, message...
3       [Action, Crime, Drama, Thriller, Following, th...
4       [Action, Adventure, ScienceFiction, John, Cart...
                              ...
4804    [Action, Crime, Thriller, El, Mariachi, just, ...
4805    [Comedy, Romance, A, newlywed, couple's, honey...
4806    [Comedy, Drama, Romance, TVMovie, "Signed,, Se...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Documentary, Ever, since, the, second, grade,...
Name: tag, Length: 4806, dtype: object

In [ ]:
# def convert(text):
#   for i in text:
#     i=i.lower()
df['tag']=df['tag'].apply(lambda x:" ".join(x))

<ipython-input-184-52d85df184fe>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag']=df['tag'].apply(lambda x:" ".join(x))

In [ ]:
# convert([["Action","Adventure"],["Action","Crime"]])
df['tag']=df['tag'].apply(lambda x: x.lower())

<ipython-input-187-642a5c7b0220>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tag']=df['tag'].apply(lambda x: x.lower())

In [ ]:
df.head(1)

      id   title                                                tag
0  19995  Avatar  action adventure fantasy sciencefiction in the...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vector = cv.fit_transform(df['tag']).toarray()

In [ ]:
vector.shape

(4806, 5000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(vector)

In [ ]:
similarity

array([[1.        , 0.07142857, 0.05143445, ..., 0.02326211, 0.02571722,
        0.        ],
       [0.07142857, 1.        , 0.07715167, ..., 0.02326211, 0.        ,
        0.        ],
       [0.05143445, 0.07715167, 1.        , ..., 0.02512595, 0.        ,
        0.        ],
       ...,
       [0.02326211, 0.02326211, 0.02512595, ..., 1.        , 0.07537784,
        0.05025189],
       [0.02571722, 0.        , 0.        , ..., 0.07537784, 1.        ,
        0.05555556],
       [0.        , 0.        , 0.        , ..., 0.05025189, 0.05555556,
        1.        ]])

In [ ]:
index=df[df['title'] == 'The Lego Movie'].index[0]

None

In [ ]:
def recommend(movie):
  index = df[df['title'] == movie].index[0]
  # distances=sorted
  distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
  for i in distances[1:6]:
        print(df.iloc[i[0]].title)

In [ ]:
recommend('Gandhi')

The Wind That Shakes the Barley
A Passage to India
Ramanujan
Guiana 1838
Chariots of Fire